---

- name: Ensure yum-utils package is installed
  yum:
    name: yum-utils
    state: present

- name: Ensure all necessary CentOS repositories are enabled for this system
  command: >
    yum-config-manager --enable base updates extras
