---

- name: Determine if the system has a attached valid Red Hat subscription
  shell: >
    subscription-manager status | grep -o Current
  register: subscription_status
  changed_when: False
  failed_when: subscription_status.rc > 1

- name: Ensure the system is registered with a Red Hat subscription using an activation key
  redhat_subscription:
    state: present
    org_id: "{{ rhel_org_id }}"
    activationkey: "{{ rhel_activation_key }}"
    force_register: "{{ 'yes' if subscription_status.rc == 0 else 'no' }}"
  when: rhel_activation_key != ""

- name: Ensure the system is registered with a Red Hat subscription using a poolid
  redhat_subscription:
    state: present
    username: "{{ rhel_username }}"
    password: "{{ rhel_password }}"
    pool_ids: "{{ rhel_pool_id }}"
    force_register: "{{ 'yes' if subscription_status.rc == 0 else 'no' }}"
  when: rhel_pool_id != ""

- name: Ensure all necessary RHEL7 repositories are enabled for this system
  command: >
    subscription-manager repos
    --enable=rhel-7-server-rpms
    --enable=rhel-7-server-optional-rpms
    --enable=rhel-7-server-supplementary-rpms
    --enable=rhel-7-server-extras-rpms

- name: Insert exclude list in yum.conf file
  lineinfile:
    path: /etc/yum.conf
    insertafter: '^installonly_limit='
    line: "exclude={{ exclude_list }}"
    state: present
  when: ansible_domain == "library.ucla.edu"
